# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'audioDNSUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for audioDNSUI
  pod 'AWSCognito'
  pod 'AWSS3'
  pod 'AWSCore'

  target 'audioDNSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'audioDNSUIUITests' do
    # Pods for testing
  end

end
